### ISSUE TITLE
Installation Failure on Mac OS X

### ISSUE THREAD

**Issue by steveatkin** [strongloop/loopback-connector-db2z#3]
Loopback connector fails to install on Mac. See screen shot.
<img width="872" alt="screen shot 2016-09-03 at 8 19 27 am" src="https://cloud.githubusercontent.com/assets/5531596/18224789/2e178e46-71af-11e6-8d4e-7eae7f99e93c.png">

**Comment by superkhau** [comment]
This issue was moved to strongloop/loopback#2723
