### ISSUE TITLE
dropTable function fails with "<string>.includes" line on ubuntu

### ISSUE THREAD

**Issue by realkendrickren** [strongloop/loopback-connector-db2z#34]
### Bug or feature request

- [X ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
The error happened when using autoMigrate feature to upgrade a table with strongloop on Ubuntu 16.04.1 connecting to a DB2 z/OS database.

The error was caused by the line -----> if (!err.toString().includes('42704')) {   <------ in the function dropTable of ibmdb.js under "loopback-connector-db2z/node_modules/loopback-ibmdb/lib" folder.

After changing the line to -------> if (err.toString().indexOf('42704')>-1) {  <----------- and rerunning the code, the logic can proceed correctly.

Can you take a look?

### Additional information (Node.js version, LoopBack version, etc)
node v0.12.7 and strongloop v6.0.3

**Comment by qpresley** [comment]
Looks simple enough .. will need some credentials to validate.

**Comment by qpresley** [comment]
Going to have to check but this looks like an issue with Node 0.12.  It seems to be working fine with my Node V4 environment.  Since Node 0.12 is no longer supported the best option is for you to move up.  Will verify this fails in Node 0.12 before closing.
