### ISSUE TITLE
Failed to do autoMigrate to create tables

### ISSUE THREAD

**Issue by realkendrickren** [strongloop/loopback-connector-db2z#35]
### Bug or feature request

- [X ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
An error happened when using autoMigrate feature to create the tables for the first time while the backend db2 z/OS database doesn't have any tables.

The error happened at the line 348 of the logic of fetching more rows in odbc.js under folder "loopback-connector-db2z/node_modules/loopback-ibmdb/node_modules/ibm_db/lib". It looks that the logic doesn't handle the case when no more record is in the resultset, as the result, an exception will be thrown out, and abort the execution.

Can you please take a look?

### Additional information (Node.js version, LoopBack version, etc)
node.js version is 0.12.7 and strongloop version is v6.0.3
Running on Ubuntu 16.04.1

**Comment by qpresley** [comment]
We will definitely need creds for a system to make these changes.  Also, you are running on an unsupported version of Node so you may want to move up to V4 or V6.  You can email myself and @ssh24 on this issue.
